############# English navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = "/"
weight = 1

[[main]]
name = "Giới thiệu"
url = "about/"
weight = 2

[[main]]
name = "Lĩnh vực hoạt động"
url = "elements/"
weight = 3

[[main]]
name = "Liên hệ"
url = "contact/"
weight = 4

[[main]]
name = "Tư vấn pháp luật"
url = "blog/"
weight = 5




# footer menu
[[footer]]
name = "Giới thiệu"
url = "about/"
weight = 1

[[footer]]
name = "Lĩnh vực hoạt động"
url = "elements/"
weight = 2

[[footer]]
name = "Bảo mật"
url = "privacy-policy/"
weight = 3
